server:
  port: 11000

spring:
  application:
    name: totoro-user
  datasource:
    url: jdbc:postgresql://localhost:5432/totoro
    username: postgres
    password: lovelive
  flyway:
    schemas: public
    baseline-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

management:
  endpoints:
    web:
      expose: '*'
    jmx:
      expose: '*'


