server:
  port: 9876

spring:
  application:
    name: totoro-web
  datasource:
    url: jdbc:postgresql://localhost:5432/totoro
    username: postgres
    password: lovelive
  redis:
    host: localhost
    port: 6379
  flyway:
    schemas: public
    baseline-on-migrate: true


mybatis:
    type-aliases-package: xyz.gosick.totoro.user.model
