server:
  port: 9876

spring:
  application:
    name: totoro-web
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/totoro?autoReconnect=true&useSSL=false
    username: root
    password: lovelive
  redis:
    host: localhost
    port: 6379



mybatis:
    type-aliases-package: xyz.gosick.totoro.user.model